config/routes.rb
MyStore::Application.routes.draw do
  # get ':controller(/:action(/:id))'
  resources :items do
    get :upvote, on: :member
    get :expensive, on: :collection
  end
end

app/models/item.rb
class Item < ActiveRecord::Base
  validates :price, numericality: { greater_than: 0, allow_nil: true }
  validates :name, :description, presence: true

  belongs_to :category

  after_initialize { p "initialized" }
  after_save       { p "saved" }
  after_create     { p "created"; } # ItemMailer.new_item_created(self).deliver # category.inc(:items_count, 1) }
  after_update     { p "updated" }
  after_destroy    { p "destroyed" } # category.inc(:items_count, -1) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

    def render_403
      render file: 'public/403.html', status: 403
    end

    def render_404
      render file: 'public/404.html', status: 404
    end

    def check_if_admin
      render_403 unless params[:admin]
    end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  before_filter :find_item, only: [:show, :edit, :update, :destroy, :upvote]
  before_filter :check_if_admin, only: [:edit, :update, :new, :create, :destroy]

  def index
    @items = Item.all
    # render text: @items.map { |i| "#{i.name}: #{i.price}"}.join("<br>")
  end

  def expensive
    @items = Item.where("price > 1000")
    render "index"
  end

  # /items/1 GET
  def showc
    unless @item
      render text: "404 Not found", status: 404
    end
  end

  # /items/new GET
  def new
    @item = Item.new
  end

  # /items/1/edit GET
  def edit
  end

  # /items POST
  def create
    @item = Item.create(item_params)
    if @item.errors.empty?
      redirect_to item_path(@item)
    else
      render "new"
    end
  end

  # /items/1 PUT + workaround POST
  def update
    @item.update_attributes(item_params)
    if @item.errors.empty?
      redirect_to item_path(@item)
    else
      render "edit"
    end
  end

  # /items/1 DELETE + workaround POST
  def destroy
    @item.destroy
    redirect_to action: "index"
  end

  def upvote
    @item.increment!(:votes_count)
    redirect_to action: "index"
  end

private
  def item_params
    params.require(:item).permit(:name, :description, :weight, :price, :real)
  end

  def find_item
    @item = Item.where(id: params[:id]).first
    render_404 unless @item
  end
end
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/edit.html.erb
<h1>Edit item</h1>
<%= form_for @item do |f| %>

<p>price: <%= f.text_field :price %>
<p>name: <%= f.text_field :name %>
<p>real: <%= f.text_field :real %>
<p>weight: <%= f.text_field :weight %>
<p>description: <%= f.text_field :description %>


<p> <%= f.submit "Отредактировать товар" %></p> 
<% end %>

app/views/items/index.html.erb
<h1>Items</h1>

<% if @items.empty? %>
  <b>No items in store</b>
<% else %>
  <table>
  <tr>
    <th>ID</th>
    <th>Name</th>
    <th>Price</th>
    <th>Edit</th>
    <th>Delete</th>
    <th>Rating</th>
  </tr>

  <% @items.each do |i| %>
    <tr>
      <td><%= i.id %></td>
      <td><%= link_to i.name, item_path(i) %></td>
      <td><%= i.price %></td>
      <td><%= link_to "edit", edit_item_path(i) %></td>
      <td><%= link_to "delete #{i.id}", item_path(i), method: :delete, data: { confirm: "Are you sure?" } %></td>
      <td>Rating: <%= i.votes_count %>, <%= link_to "+", upvote_item_path(i) %></td>
    </tr>
  <% end %>
  </table>
<% end %>

app/views/items/new.html.erb
<h1>Create new item</h1>

<%= form_for @item do |f| %>

<p>price: <%= f.text_field :price %>
<p>name: <%= f.text_field :name %>
<p>real: <%= f.text_field :real %>
<p>weight: <%= f.text_field :weight %>
<p>description: <%= f.text_field :description %>


<p> <%= f.submit "Создать товар" %></p> 
<% end %>

app/views/items/show.html.erb
<h1><%= @item.name %></h1>

<ul>
<li>Цена <%= @item.price %> руб.</li>
<li>Опис <%= @item.description %></li>
<li>Вес <%= @item.weight %> кг</li>

</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyStore</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>